---
# This is a file of variables that will be processed in job_conf.yml.j2
# This is needed, because it contains other variables

galaxy_jobconf:
  plugin_workers: 2
  handlers:
    count: "{{ galaxy_systemd_handlers }}"
    assign_with: db-skip-locked
    max_grab: 4
    ready_window_size: 8
  plugins:
    - id: condor
      load: galaxy.jobs.runners.condor:CondorJobRunner
    - id: local
      load: galaxy.jobs.runners.local:LocalJobRunner
    - id: pulsar_eu_egi01
      load: galaxy.jobs.runners.pulsar:PulsarMQJobRunner
      params:
        amqp_url: "pyamqp://galaxy_egi01:{{ rabbitmq_password_galaxy_egi01 }}@mq.galaxyproject.eu:5671//pulsar/galaxy_egi01?ssl=1"
        galaxy_url: "https://usegalaxy.eu"
        manager: production
        amqp_acknowledge: "true"
        amqp_ack_republish_time: 300
        amqp_consumer_timeout: 2.0
        amqp_publish_retry: "true"
        amqp_publish_retry_max_retries: 60
  default_destination: tpv_dispatcher
  destinations:
    - id: local
      runner: local
    - id: tpv_dispatcher
      runner: dynamic
      type: python
      function: map_tool_to_destination
      rules_module: tpv.rules
      tpv_config_files:
        - "{{ galaxy_config_dir }}/total_perspective_vortex/tool_defaults.yml"
        - "https://raw.githubusercontent.com/galaxyproject/tpv-shared-database/main/tools.yml"
        - "{{ galaxy_config_dir }}/total_perspective_vortex/destinations.yml"
        - "{{ galaxy_config_dir }}/total_perspective_vortex/tools.yml"
  limits:
    - type: "destination_user_concurrent_jobs"
      id: "condor_tpv"
      value: "10"
    - type: "walltime"
      value: "'148:00:00'"
    - type: "output_size"
      value: "'20GB'"
    - type: "registered_user_concurrent_jobs"
      value: "5"
    - type: "anonymous_user_concurrent_jobs"
      value: "0"
    # - type: "destination_user_concurrent_jobs"
    #   id: "sh_fdid_condor_docker_ie"
    #   value: "3"
    # - type: "destination_user_concurrent_jobs"
    #   id: "sh_fdid_condor_docker_ie_interactive"
    #   value: "3"
    - type: "destination_user_concurrent_jobs"
      id: "sh_fdid_condor_intensive_jobs"
      value: "5"
