---
# ALL tags must be with dashes (-) instead of underscores (_)
tools:
  __DATA_FETCH__:
    cores: 1
    mem: 3
    gpus: 0
    rules:
      - id: no-pulsar
        if: user is not None
        execute: |
            from tpv.core.entities import Tag, TagSetManager, TagType

            user_preferences = user.extra_preferences
            pulsar_tag = user_preferences.get("distributed_compute|remote_resources", "None")
            pulsar_tag = Tag("scheduling", pulsar_tag, TagType.REQUIRE) if pulsar_tag != "None" else None

            entity.tpv_tags.tags = [
                tag
                for tag in entity.tpv_tags.tags
                if tag != pulsar_tag
            ]
    env:
      TEMP: /data/1/galaxy_db/tmp

  toolshed.g2.bx.psu.edu/repos/iuc/enasearch_search_data/enasearch_search_data/.*:
    scheduling:
      require:
        - conda
        - singularity

  toolshed.g2.bx.psu.edu/repos/iuc/fasta_stats/fasta-stats/.*:
    rules:
      - if: input_size >= 0.01
        cores: 3
