collections:
  - name: community.docker
    version: 1.9.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: community.rabbitmq
    version: 1.1.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: devsec.hardening
    version: 8.7.0
    source: https://galaxy.ansible.com
    type: galaxy
  - name: usegalaxy_eu.handy
    version: 3.0.1
    source: https://galaxy.ansible.com

roles:
  - name: galaxyproject.galaxy
    src: https://github.com/galaxyproject/ansible-galaxy
    version: 0.10.15
  - name: galaxyproject.cvmfs
    src: https://github.com/usegalaxy-eu/ansible-cvmfs
    version: master
  - name: usegalaxy_eu.ansible_nginx_upload_module
    version: 1.0.0
  - name: usegalaxy-eu.nginx
    src: https://github.com/usegalaxy-eu/ansible-nginx
    version: master
  - src: galaxyproject.postgresql_objects
    version: 1.2.0
  - name: usegalaxy-eu.ansible-postgresql
    src: https://github.com/usegalaxy-eu/ansible-postgresql
    version: main
  - src: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.repo-epel
    version: 3.1.0
  - name: geerlingguy.java
    version: 2.2.0
  - name: galaxyproject.gxadmin
    version: 0.0.8
  - name: usegalaxy-eu.certbot
    src: https://github.com/usegalaxy-eu/ansible-certbot
    version: 0.1.5
  - name: usegalaxy_eu.galaxy_systemd
    version: 2.1.0
  - name: usegalaxy-eu.autoupdates
    src: https://github.com/usegalaxy-eu/ansible-autoupdates
    version: 0.0.1
  - name: usegalaxy_eu.htcondor
    version: 1.0.1
  - name: usegalaxy_eu.rustus
    version: 0.2.0
  - name: usegalaxy_eu.rabbitmqserver
    version: 1.4.4
  - name: influxdata.chrony
    src: https://github.com/usegalaxy-eu/ansible-chrony
    version: 0.1.0
  - name: usegalaxy_eu.tpv_auto_lint
    version: 0.2.1
  - name: geerlingguy.redis
    version: 1.8.0
  - name: galaxyproject.miniconda
    version: 0.3.1
  - name: galaxyproject.nginx
    version: 0.6.4
  - name: usegalaxy_eu.flower
    version: 1.0.2
  - name: usegalaxy_eu.galaxy_subdomains
    version: 0.0.13
  - name: usegalaxy-eu.fslimit
    src: https://github.com/usegalaxy-eu/ansible-fslimit
    version: main
  - src: usegalaxy_eu.apptainer
    version: 0.0.1
  - src: galaxyproject.pulsar
    version: 1.0.10
