---
- hosts: upload_server
  become: true
  become_user: root
  vars:
    hostname: "{{ inventory_hostname }}"
    # Make sure that this directory exists otherwise rustus service won't start
    upload_dir_main: /data/jwd01/tus_upload/main
    rustus_version: "0.7.4"
    rustus_instances:
      - name: main_uploads
        user: "{{ galaxy_user.name }}"
        group: "{{ galaxy_group.name }}"
        working_directory: "{{ upload_dir_main }}"
        args:
          - --host "{{ inventory_hostname }}"
          - --port 1081
          - "--data-dir {{ upload_dir_main }}"
          - --hooks-http-urls "https://usegalaxy.esgwps.uno/api/upload/hooks"
          - --hooks-http-proxy-headers "X-Api-Key,Cookie"
          - --hooks "pre-create"
          - --hooks-format tusd
          - --url "/api/upload/resumable_upload"
          - --max-body-size 20000000
          - --info-storage "file-info-storage" --info-dir "{{ upload_dir_main }}"
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "python3",
            "python3-devel",
            "firewalld"
          ]

    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - ansible.posix.firewalld:
        zone: public
        port: 1080-1081/tcp
        permanent: true
        state: enabled

    # Without setting this context chronyd service won't start
    - name: Semanage chronyd port udp 1123
      seport:
        ports: 1123
        proto: udp
        setype: chronyd_port_t
        state: present
  post_tasks:
    - name: Set authorized SSH key (galaxy user)
      ansible.posix.authorized_key:
        user: "{{ galaxy_user.name }}"
        state: present
        key: "{{ item }}"
      loop:
        - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOBINXdjILF6x3WuppXyq6J2a2oSLR6waZ6txgjYJogHdIKPbI0TdReCv4EVxxYRY/NqGpHbjkqfRTsf2VgoU3U= mk@galaxy-mira"
        - "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACB5Q5blymkTIRSzVzXITOGvBuI7W0L9Ykwfz8LJGPraaGVPiezzFGvjhqwX+EyCqQPt7JprR5mimJRw/JN3nBXWAHjekvmB5FuILkk6m5fOiQJ5QhRMyQ5GfxODAvGbHpTuWHbYJLWD5fhcboKPxlXOWy4xY9kDZVuQvEKisNKYBsFLA== sanjay"
        - "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBABRaLHL8mgW86rbtdUh6TY4rs7/la8hAGeSQ3jBF7LMwYZnbS32YDMYvDq3KgNu5WqSMFvkxNm3vfTAbd8CXBfakwDBFBaD9kO0b2t4/p4VoFUsd3B2OvmTR7Bsg7OxTGJJ7aUP/SzTg+Z4NzsmHwQ9h31gfI7n/buZD4S1edQke19Y6w== dominguj@informatik.uni-freiburg.de"
  roles:
    - geerlingguy.repo-epel
    - usegalaxy_eu.handy.os_setup
    - influxdata.chrony
    - autofs
    - usegalaxy_eu.rustus
